### ISSUE TITLE
Deploy the template somewhere for folks to quickly visualize it

### ISSUE THREAD

**Issue by gabrielfior** [scio-labs/ethathon#1]
Congrats on the project, will definitely give it a spin during ETH Berlin!
As per title, would be great to deploy this on Vercel for people to quickly understand and have a "feel" for the project. Otherwise great stuff!

**Comment by wottpal** [comment]
hey @gabrielfior, thank you so much for having a look and even considering using it during the hackathon! i really want this to become a great (and lightweight) starting point for dApp development. feel free to reach out during the hackathon if you stumble across some problems.

i did some minor improvements/cleanups today, including a sample vercel-deploy like you suggested. you can find it under: https://ethathon.xyz. i even added a new section to the readme (https://github.com/ethathon/ethathon#deployment) explaining how to set up the deployment! hope that helps.

👋

**Comment by gabrielfior** [comment]
Looks excellent, thanks!
